### ISSUE TITLE
Google account registration page wording changes

### ISSUE THREAD

**Issue by tuecke** [globusonline/google-drive-registration-app#16] opened 2017-02-22 23:02 UTC
Change: Would you like to register another Google Account on this server?
To: Register another Google Account with this Globus Connect Server
Note: If there are no Google accounts registered, change "another" to "a"

Remove: You will always control who has access to your Google Drive.
(Drop this sentence from any other pages that also have it.)

Change: This Google Account will be registered under your tuecke@globusid.org identity [link another]
To: This Google Account will be registered on this Globus Connect Server with your tuecke@globusid.org identity [change]
Note: Default selection criteria should be. If the primary identity is from an approved identity provider, pick it.  Else, pick one of approved identities.    Never display an dropdown of identities on this page.  Just pick one, and then have the change link to change it.

Add a line break after the continue button: "----------  or  ------------"

Change: Continue with your existing credentials?
To: Continue with an existing registered Google Account

Change: You have already registered the following Google Accounts:
To: You have already registered the following Google Accounts on this Globus Connect Server. Select one to use it:

**Comment by tuecke** [comment] 2017-02-22 23:15
Also change: Registering a Google Account on this server, ...
To: Registering a Google Account on this Globus Connect Server, ...

**Comment by corpulentcoffee** [comment] 2017-02-22 23:25
> Change: This Google Account will be registered under your tuecke@globusid.org identity [link another]
> To: This Google Account will be registered on this Globus Connect Server with your tuecke@globusid.org identity [change]

FYI that you'll get a "change" link if you have at least one other eligible identity. I can't really have a "change" link if you have no other eligible identity to change to since it would just reveal the identity dropdown with a single option of the identity you already had before clicking "change".

**Comment by tuecke** [comment] 2017-02-23 14:04
No, the change should always be there. I may be able to add another identity from the same identity provider.  And with the redesigned change identity page, #17, the behavior if they clicked "change" in this situation would all make more sense to a user, and they can easily get back.

**Comment by tuecke** [comment] 2017-02-23 14:05
Also, what "identity dropdown"?  I don't think the main page should have an identity dropdown, but just a link to the change identity page, as described in #17

**Comment by corpulentcoffee** [comment] 2017-02-23 14:11
I'm going to close this as a duplicate of #17, then, since it doesn't make sense without #17.
Without #17, there's an identity dropdown, so I need #17.

**Closed by corpulentcoffee** 2017-02-23 14:11 UTC
