### ISSUE TITLE
List of linked identities is incomplete

### ISSUE THREAD

**Issue by tuecke** [globusonline/google-drive-registration-app#10] opened 2017-02-22 21:16 UTC
As far as I can tell, I'm logged into an account with a primary identity of tuecke@globusid.org, and a linked identity of tuecke@uchicago.edu.  But on the page for linking an identity, it only lists tuecke@globusid.org in "These identities are currently eligible for use:".

**Comment by corpulentcoffee** [comment] 2017-02-22 21:22
Can't reproduce this issue.

Can you share a screenshot of https://sandbox.globuscs.info/app/account and https://gdrive.sandbox.globuscs.info/link?client_id=d1872082-6d38-4434-818e-127f41573de6 for comparing?

**Comment by tuecke** [comment] 2017-02-22 21:22
I also ran into this Globus Auth issue on the gdrive identity linking page: https://github.com/globusonline/globus-auth/issues/920

**Comment by jaswilli** [comment] 2017-02-22 21:51
FWIW, I just set up an identity set in the same way (globus id primary, uchicago linked) and it seems to be doing the expected thing for me:

![screen shot 2017-02-22 at 3 50 16 pm](https://cloud.githubusercontent.com/assets/214142/23234132/b6e1c202-f916-11e6-9958-3fa93b048f42.png)

**Comment by corpulentcoffee** [comment] 2017-02-22 22:02
Yes, same with me:
![image](https://cloud.githubusercontent.com/assets/3958448/23234506/e8ee64de-f917-11e6-8bd4-bb3bfe6166c2.png)

@tuecke Can you open the debugger, go to the Network tab, reload the page, and copy-and-paste the output from the `whoami` call's "Response" tab?

![image](https://cloud.githubusercontent.com/assets/3958448/23234602/3d398fd2-f918-11e6-9286-c183e1f67aea.png)

**Comment by corpulentcoffee** [comment] 2017-02-23 17:30
Closing and moving to Auth.

**Closed by corpulentcoffee** 2017-02-23 17:30 UTC
